so-elastalert-test: add ability to use arguments
Security-Onion-Solutions/securityonion-elastic pull request #51
Opened 2019-03-16 03:33 UTC by weslambert

Refactor to allow use of arguments to:

- Skip verbiage and automate rule test
- Specify location of rule file to be processed
- Specify where we want the results log to be saved
- Specify if we want to trigger an actual alert
- Specify other free-form options, such as `--count-only`, `--schema-only`, `--days N`

2019-03-16 11:13 UTC, dougburks requested changes
Hi Wes,

Thanks for the PR!

Please see my suggested changes.

2019-03-16 11:13 UTC, dougburks commented on usr/sbin/so-elastalert-test
> +#!_bin/bash
```suggestion
#!/bin/bash
```

2019-03-16 11:13 UTC, dougburks commented on usr/sbin/so-elastalert-test
> +	current_rules=$(sudo ls /etc/elastalert/rules/)
```suggestion
	current_rules=$(ls /etc/elastalert/rules/)
```

2019-03-16 11:13 UTC, dougburks commented on usr/sbin/so-elastalert-test
> +	current_rules=$(sudo ls /etc/elastalert/rules/)
`so-elastic-common` should have already guaranteed that the user is running with sudo privs.  No need to call `sudo` again.

2019-03-16 11:13 UTC, dougburks commented on usr/sbin/so-elastalert-test
> +  -l <path_to_file      Write results to specified log file
```suggestion
  -l <path_to_file>      Write results to specified log file
```

2019-03-16 11:41 UTC, weslambert commented
Apologies -- copied and modified the wrong source file, so I will need to modify from the one with the latest commits and implement any other suggestions.

Thanks!

2019-03-16 14:17 UTC, bryant-treacle commented
Doug and Wes,

    FYI, the final_prompt function in so-elastalert-create-whiptail asks the individual if they want to test the rule.  If they opt to test the rule, it copies the new rule to /etc/elastalert/rules an then runs so-elastalert-test.  I tested it this morning and it works fine with the new so-elastalert-test script.  However if you want to start passing command line arguments additional parameters may need to be added to that function. 

Bryant

2019-03-16 14:25 UTC, dougburks requested changes

2019-03-16 14:25 UTC, dougburks commented on usr/sbin/so-elastalert-test
> +Create Elastalert Rule
Why change from `Test` to `Create`?

2019-03-16 14:27 UTC, weslambert commented
This was an artifact of modifying between test box and GH push box.

I originally copied that portion of code from the so-elasticsearch-template
creation script.

Thanks,
Wes
I'll correct when I get a chance.

On Sat, Mar 16, 2019, 10:25 AM Doug Burks <notifications@github.com> wrote:

> *@dougburks* requested changes on this pull request.
> ------------------------------
>
> In usr/sbin/so-elastalert-test
> <https://github.com/Security-Onion-Solutions/securityonion-elastic/pull/51#discussion_r266202850>
> :
>
> >
>  usage()
>  {
>  cat <<EOF
>
> -Test Elastalert Rule
> +Create Elastalert Rule
>
> Why change from Test to Create?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Security-Onion-Solutions/securityonion-elastic/pull/51#pullrequestreview-215316504>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQDNqBMKcSVZ0_BWx5bwD3ALpUA-gLfmks5vXP7LgaJpZM4b3lYb>
> .
>

2019-03-18 16:48 UTC, dougburks commented
> Doug and Wes,
> 
> ```
> FYI, the final_prompt function in so-elastalert-create-whiptail asks the individual if they want to test the rule.  If they opt to test the rule, it copies the new rule to /etc/elastalert/rules an then runs so-elastalert-test.  I tested it this morning and it works fine with the new so-elastalert-test script.  However if you want to start passing command line arguments additional parameters may need to be added to that function. 
> ```
> Bryant

Hi Bryant,

I've created a separate issue to update `so-elastalert-create-whiptail`:
https://github.com/Security-Onion-Solutions/security-onion/issues/1487

Thanks!

2019-03-18 16:48 UTC, merged